# Generated by Django 5.0.6 on 2024-07-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_header_leadhistory_leads_listingtype_propertyimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='generated_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='leads',
            name='landing_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNMyKN-46qd_o8Ox80dtGSfBOG2M9iFqMNjQ&s', upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leads',
            name='interests',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='community_image_url',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
