# Generated by Django 5.0.6 on 2024-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leadhistory_leads_propertyimage_property_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_units',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='brochure_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='community',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='community_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='community_image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='hand_over',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
