# Generated by Django 5.0.6 on 2024-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_available_units_property_brochure_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='generated_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='leads',
            name='landing_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leads',
            name='interests',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
