# Generated by Django 5.0.6 on 2024-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_propertyimage_remove_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='property_id',
            field=models.IntegerField(),
        ),
    ]
