# Generated by Django 5.0.6 on 2024-06-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_property_created_by_alter_property_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_units',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='brochure_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='community',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='community_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='community_image_url',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNMyKN-46qd_o8Ox80dtGSfBOG2M9iFqMNjQ&s', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='hand_over',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
