# Generated by Django 5.0.6 on 2024-06-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_property_available_units_property_brochure_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='community_image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
