# Generated by Django 5.0.6 on 2024-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_property_bedrooms_alter_propertyimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(default='https://homesigmaimages.s3.amazonaws.com/property_images/default_thumbnail.jpg', upload_to='property_images/'),
            preserve_default=False,
        ),
    ]
