# Generated by Django 5.0.6 on 2024-07-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_property_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Navigation'},
        ),
        migrations.AlterField(
            model_name='property',
            name='community_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
