# Generated by Django 5.0.6 on 2024-07-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leads_generated_by_leads_landing_link_and_more'),
        ('core', '0021_alter_property_bedrooms_alter_property_hand_over'),
    ]

    operations = [
    ]
