# Generated by Django 5.0.6 on 2024-07-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leads_generated_by_leads_landing_link_and_more'),
        ('core', '0022_merge_20240706_2017'),
    ]

    operations = [
    ]
